behaviors:
  MayanAdventureLearning:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 2048
      learning_rate: 0.0001
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 30000
    threaded: true
    framework: pytorch
environment_parameters:
  level:
    curriculum:
    - name: Lesson0
      completion_criteria:
        measure: reward
        behavior: MayanAdventureLearning
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 0.8
      value: 0.0
    - name: Lesson1
      completion_criteria:
        measure: reward
        behavior: MayanAdventureLearning
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 1.6
      value: 1.0
    - name: Lesson2
      completion_criteria:
        measure: reward
        behavior: MayanAdventureLearning
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 2.2
      value: 2.0
    - name: Lesson3
      value: 3.0
